export const stores = [
  {
    id: 0,
    name: "EU's Closet and Travels",
    image_url: require('../../assets/images/stores/eus-closet.jpg'),
    category: ['Jewelries'],
    rating: 5.0,
    deliveryTime: [2, 3],
    location: 'Port-Harcourt',
    products: [
      {
        id: 0,
        name: 'Hublot Watch',
        image_url: require('../../assets/images/featured_items/hublot.jpg'),
        price: 10000,
        discount: 30,
        timesBought: 400,
        // store: "Zella's place",
      },
      {
        id: 1,
        name: 'Comfortable Headwrap',
        image_url: require('../../assets/images/featured_items/headwrap.jpg'),
        price: 1500,
        discount: 45,
        timesBought: 590,
        // store: "Zella's place",
      },
      {
        id: 2,
        name: 'Female Top',
        image_url: require('../../assets/images/featured_items/top.jpg'),
        price: 8000,
        discount: 30,
        timesBought: 76,
        // store: "Zella's place",
      },
      {
        id: 3,
        name: 'Hublot Watch 2',
        image_url: require('../../assets/images/featured_items/hublot.jpg'),
        price: 10000,
        discount: 30,
        timesBought: 400,
        // store: "Zella's place",
      },
      {
        id: 4,
        name: 'Comfortable Headwrap 2',
        image_url: require('../../assets/images/featured_items/headwrap.jpg'),
        price: 1500,
        discount: 45,
        timesBought: 590,
        // store: "Zella's place",
      },
      {
        id: 5,
        name: 'Female Top 2',
        image_url: require('../../assets/images/featured_items/top.jpg'),
        price: 8000,
        discount: 30,
        timesBought: 76,
        // store: "Zella's place",
      },
    ],
  },
  {
    id: 1,
    name: 'Petmeeys Closet',
    image_url: require('../../assets/images/stores/petmeezy.jpg'),
    category: ['Fashion'],
    rating: 5.0,
    deliveryTime: [1, 3],
    location: 'Lagos',
    products: [
      {
        id: 0,
        name: 'Colourful stylish handbag',
        image_url: require('../../assets/images/featured_items/bags.jpg'),
        price: 4000,
        discount: 15,
        timesBought: 50,
        // store: "Zella's place",
      },
      {
        id: 1,
        name: 'Female handbag',
        image_url: require('../../assets/images/featured_items/whitebag.jpg'),
        price: 9000,
        discount: 35,
        timesBought: 632,
        // store: "Zella's place",
      },
      {
        id: 2,
        name: 'Universal slide',
        image_url: require('../../assets/images/featured_items/slides.jpg'),
        price: 12000,
        discount: 20,
        timesBought: 954,
        // store: "Zella's place",
      },
      {
        id: 3,
        name: 'Colourful stylish handbag 2',
        image_url: require('../../assets/images/featured_items/bags.jpg'),
        price: 4000,
        discount: 15,
        timesBought: 50,
        // store: "Zella's place",
      },
      {
        id: 4,
        name: 'Female handbag 2',
        image_url: require('../../assets/images/featured_items/whitebag.jpg'),
        price: 9000,
        discount: 35,
        timesBought: 632,
        // store: "Zella's place",
      },
    ],
  },
  {
    id: 2,
    name: 'Ajenny Home of Luxury',
    image_url: require('../../assets/images/stores/anny.jpg'),
    category: ['Fashion'],
    rating: 5.0,
    deliveryTime: [3, 6],
    location: 'Abuja',
    products: [
      {
        id: 0,
        name: "Men's Jeans",
        image_url: require('../../assets/images/featured_items/jeans.jpg'),
        price: 23000,
        discount: 45,
        timesBought: 136,
        // store: "Zella's place",
      },
      {
        id: 1,
        name: 'Universal shorts',
        image_url: require('../../assets/images/featured_items/shorts.jpg'),
        price: 6000,
        discount: 20,
        timesBought: 353,
        // store: "Zella's place",
      },
      {
        id: 2,
        name: 'vca',
        image_url: require('../../assets/images/featured_items/vca.jpg'),
        price: 3000,
        discount: 30,
        timesBought: 49,
        // store: "Zella's place",
      },
    ],
  },

  {
    id: 3,
    name: "Millie's Garrage",
    image_url: require('../../assets/images/stores/4.png'),
    category: ['Fashion', 'Phones'],
    rating: 5.0,
    deliveryTime: [2, 3],
    location: 'Owerri',
    products: [
      {
        id: 0,
        name: 'High Top Shoe',
        image_url: require('../../assets/images/featured_items/shoe2.jpg'),
        price: 26000,
        discount: 24,
        timesBought: 270,
        // store: "Zella's place",
      },
      {
        id: 1,
        name: 'Male high top',
        image_url: require('../../assets/images/featured_items/shoe3.jpg'),
        price: 39000,
        discount: 18,
        timesBought: 370,
        // store: "Zella's place",
      },
      {
        id: 2,
        name: "Men's Stylish High shoe ",
        image_url: require('../../assets/images/featured_items/show4.jpg'),
        price: 305500,
        discount: 10,
        timesBought: 93,
        // store: "Zella's place",
      },
    ],
  },
];

export const categories = [
  {
    name: 'All Stores',
    image_url: require('../../assets/images/categories/store.png'),
  },
  {
    name: 'Fashion',
    image_url: require('../../assets/images/categories/clothes-hanger.png'),
  },
  {
    name: 'Phones',
    image_url: require('../../assets/images/categories/smartphone.png'),
  },
  {
    name: 'Jewelries',
    image_url: require('../../assets/images/categories/diamond-ring.png'),
  },
  {
    name: 'Cosmetics',
    image_url: require('../../assets/images/categories/cosmetics.png'),
  },
  {
    name: 'Gaming',
    image_url: require('../../assets/images/categories/game-console.png'),
  },
  {
    name: 'Electronics',
    image_url: require('../../assets/images/categories/television.png'),
  },
  {
    name: 'Home',
    image_url: require('../../assets/images/categories/home.png'),
  },
  {
    name: 'Baby',
    image_url: require('../../assets/images/categories/baby-boy.png'),
  },
  {
    name: 'Office',
    image_url: require('../../assets/images/categories/workplace.png'),
  },
];
